numWorkers: 10
workerRunSeconds: 10
ipaddr: "127.0.0.1"
port: 10022
username: "root"
password: "password"
enableDownload: false
localTempfileDir: "/tmp/sftp/local/"
remoteTempfileDir: "/tmp/sftp/remote/"
