worker:
  numWorkers: 1
  workerRunSeconds: 5
  workerNumRequests: 1
ssh:
  ipaddr: "127.0.0.1"
  port: 10022
  username: "root"
  password: "qweiop"
sftp:
  numSftpPerSsh: 0
  enableDownload: false
  localTempfileDir: "/tmp/sftp/local/"
  remoteTempfileDir: "/tmp/sftp/remote/"
cmd:
  numCmdPerSsh: 1
  command: "echo ABC"
  renderOutput: false
