worker:
  numWorkers: 10
  workerRunSeconds: 10
  workerNumRequests: -1
ssh:
  ipaddr: "127.0.0.1"
  port: 22
  username: "root"
  password: "password"
sftp:
  numSftpPerSsh: 1
  enableDownload: false
  localTempfileDir: "/tmp/sftp/local/"
  remoteTempfileDir: "/tmp/sftp/remote/"
cmd:
  numCmdPerSsh: 0
  command: "echo ABC"
  renderOutput: false
